### ISSUE TITLE
Individual Restaurant Menu List

### ISSUE THREAD

**Issue by avicndugu** [chingu-voyages/v36-geckos-team-11#12]
**__Individual Restaurant Menu List__**
Display and offer a way to select items from one individual restaurant 

**__Major User Stories/tasks__**
- [ ] User can view all the menu items available on from a restaurant.
- [ ] User can select individual items on the menu list.
- [ ] User can go back to the main list of all restaurants.
- [ ] User can click to view a list of selected items[Checkout page] 

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
