### ISSUE TITLE
Checkout Page Section

### ISSUE THREAD

**Issue by avicndugu** [chingu-voyages/v36-geckos-team-11#16]
**__Checkout Page Section__**
View the current order and offer options to modify it or proceed to payments 

**__Major User Stories/tasks__**
- [ ] Users can view a list of all ordered items
- [ ] User can modify the order by adding or reducing quantity of items.
- [ ] User can modify order by removing individual item.
- [ ] User can confirm order and proceed to Delivery section

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
